# Generated by Django 5.2.5 on 2025-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='hotelorderitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelorderitem',
            name='oncredit',
            field=models.BooleanField(default=False),
        ),
    ]
