# Generated by Django 5.2.5 on 2025-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_hotelorderitem_created_at_hotelorderitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorderitem',
            name='oncredit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
