# Generated by Django 5.2.5 on 2025-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_alter_hotelorderitem_oncredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='total_order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
