# Generated by Django 5.2.5 on 2025-12-09 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone  # <--- Add this import

class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_alter_fooditem_created_by_alter_hotelorderitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorderitem',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True,default=timezone.now, auto_now_add=True),  # <--- FIXED
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelorderitem',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # <--- FIXED
            preserve_default=False,
        ),
    ]
