# Generated by Django 5.2.5 on 2025-12-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_alter_hotelorderitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorderitem',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelorderitem',
            name='oncredit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
