# Generated by Django 5.2.5 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0006_hotelorderitem_name_hotelorderitem_oncredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorderitem',
            name='oncredit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hotelorderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
