# Generated by Django 5.2.5 on 2025-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_alter_hotelorderitem_oncredit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
