"""
Django settings for LaundryConfig project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
import dj_database_url
from LaundryConfig.env import BASE_DIR, env
from datetime import timedelta


from decouple import config

# import dj_database_url
# from decouple import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {"1", "true", "yes", "on"}

# This allows your Render URL to be a valid hos*t




# NPM_BIN_PATH = os.environ.get("NPM_BIN_PATH", None)
# Application definition

INSTALLED_APPS = [
    # IMPORTANT: Add whitenoise to INSTALLED_APPS for it to be recognized
    # by collectstatic and for its static file storage engine to work.
    'whitenoise.runserver_nostatic',
    'multiselectfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'LaundryApp',
    'axes',
    'APIApp',
    'compressor',
    "widget_tweaks",
    'OpenSSL',
    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
    "django_filters",
    'django_daraja',
    'HotelApp.apps.HotelappConfig',
]

MIDDLEWARE = [
   
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'axes.middleware.AxesMiddleware', 
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',  # Disabled for API development
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

AXES_FAILURE_LIMIT = 5          # max attempts
AXES_COOLOFF_TIME = 1           # hours
AXES_RESET_ON_SUCCESS = True

AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']




EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_AUTO_FIELD = env('DEFAULT_AUTO_FIELD')

API_KEY = env("ROAMTECH_API_KEY")
PARTNER_ID = env("ROAMTECH_PARTNER_ID")
SHORTCODE = env("SHORTCODE")


# For production: use real SMTP (example with Gmail)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # not your Gmail password, use App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = DEFAULT_FROM_EMAIL

AUTH_USER_MODEL = 'LaundryApp.UserProfile'
ROOT_URLCONF = 'LaundryConfig.urls'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  # Important for tracking last login

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}



FRONTEND_BUILD_DIR = os.path.join(BASE_DIR, 'Front-end', 'dist')

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    'LaundryConfig.authentication.EmailBackend',  # custom email login backend
    'django.contrib.auth.backends.ModelBackend',
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Front-end','dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
             'builtins': [
                'django.contrib.humanize.templatetags.humanize',  # Add this
            ],
        },
    },
]

WSGI_APPLICATION = 'LaundryConfig.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Configure static files for production

STATIC_URL = '/static/'

# Tell Django where to collect all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

STATICFILES_DIRS = [
    os.path.join(FRONTEND_BUILD_DIR, "assets"),
    FRONTEND_BUILD_DIR,  # Include root files like images from public folder
]


# Tell Whitenoise to compress your static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'LaundryApp': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# CORS settings


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'LaundryApp.pagination.CustomPageNumberPagination',
    
}

# Disable APPEND_SLASH to prevent issues with API endpoints
APPEND_SLASH = False


# Daraja / M-PESA configuration
MPESA_ENVIRONMENT = env("MPESA_ENVIRONMENT", default="sandbox").strip().lower()
if MPESA_ENVIRONMENT not in {"sandbox", "production"}:
    MPESA_ENVIRONMENT = "sandbox"

MPESA_CONSUMER_KEY = env("MPESA_CONSUMER_KEY", default="")
MPESA_CONSUMER_SECRET = env("MPESA_CONSUMER_SECRET", default="")

# Shortcode used for transactions.
# Sandbox default is 174379. Production must be set in environment.
MPESA_SHORTCODE = env(
    "MPESA_SHORTCODE",
    default="174379" if MPESA_ENVIRONMENT == "sandbox" else "",
)

# Shortcode for Lipa na M-PESA Online (STK Push).
# If not set, fallback to MPESA_SHORTCODE.
MPESA_EXPRESS_SHORTCODE = env("MPESA_EXPRESS_SHORTCODE", default=MPESA_SHORTCODE)

# Valid values: paybill | till_number
raw_shortcode_type = env("MPESA_SHORTCODE_TYPE", default="paybill")
MPESA_SHORTCODE_TYPE = (
    "till_number"
    if raw_shortcode_type in {"till", "till_number", "buygoods"}
    else "paybill"
)

# Sandbox passkey is publicly available; production passkey is issued by Safaricom.
MPESA_PASSKEY = env(
    "MPESA_PASSKEY",
    default=(
        "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
        if MPESA_ENVIRONMENT == "sandbox"
        else ""
    ),
)

# Used by B2C/B2B/TransactionStatus/Reversal APIs.
MPESA_INITIATOR_USERNAME = env("MPESA_INITIATOR_USERNAME", default="")
MPESA_INITIATOR_SECURITY_CREDENTIAL = env(
    "MPESA_INITIATOR_SECURITY_CREDENTIAL",
    default="",
)

# Must be a public HTTPS URL reachable by Safaricom API gateway.
MPESA_CALLBACK_URL = env("MPESA_CALLBACK_URL", default="")

