# Generated by Django 5.2.5 on 2026-01-13 06:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other'), ('None', 'None')], db_index=True, default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='itemtype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Clothing', 'Clothing'), ('Bedding', 'Bedding'), ('Household items', 'Household items'), ('Footwares', 'Footwares')], db_index=True, default='Clothing', max_length=100),
        ),
    ]
